/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.SocketCmd.SettingsStage', null, global);
goog.exportSymbol('proto.SocketCmd.Stage', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocketCmd.SettingsStage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.SocketCmd.SettingsStage.repeatedFields_, null);
};
goog.inherits(proto.SocketCmd.SettingsStage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SocketCmd.SettingsStage.displayName = 'proto.SocketCmd.SettingsStage';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.SocketCmd.SettingsStage.repeatedFields_ = [13,35];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocketCmd.SettingsStage.prototype.toObject = function(opt_includeInstance) {
  return proto.SocketCmd.SettingsStage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocketCmd.SettingsStage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocketCmd.SettingsStage.toObject = function(includeInstance, msg) {
  var f, obj = {
    cmdcode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    identity: jspb.Message.getFieldWithDefault(msg, 2, ""),
    oppositeid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    timetoken: jspb.Message.getFieldWithDefault(msg, 4, ""),
    serverid: jspb.Message.getFieldWithDefault(msg, 6, 0),
    lightnoList: jspb.Message.getRepeatedField(msg, 13),
    stageList: jspb.Message.toObjectList(msg.getStageList(),
    proto.SocketCmd.Stage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocketCmd.SettingsStage}
 */
proto.SocketCmd.SettingsStage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocketCmd.SettingsStage;
  return proto.SocketCmd.SettingsStage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocketCmd.SettingsStage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocketCmd.SettingsStage}
 */
proto.SocketCmd.SettingsStage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCmdcode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setIdentity(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOppositeid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTimetoken(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setServerid(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.addLightno(value);
      break;
    case 35:
      var value = new proto.SocketCmd.Stage;
      reader.readMessage(value,proto.SocketCmd.Stage.deserializeBinaryFromReader);
      msg.addStage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocketCmd.SettingsStage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocketCmd.SettingsStage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocketCmd.SettingsStage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocketCmd.SettingsStage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCmdcode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIdentity();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOppositeid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTimetoken();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getServerid();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getLightnoList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      13,
      f
    );
  }
  f = message.getStageList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      35,
      f,
      proto.SocketCmd.Stage.serializeBinaryToWriter
    );
  }
};


/**
 * optional string cmdCode = 1;
 * @return {string}
 */
proto.SocketCmd.SettingsStage.prototype.getCmdcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.SocketCmd.SettingsStage.prototype.setCmdcode = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string identity = 2;
 * @return {string}
 */
proto.SocketCmd.SettingsStage.prototype.getIdentity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.SocketCmd.SettingsStage.prototype.setIdentity = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string oppositeId = 3;
 * @return {string}
 */
proto.SocketCmd.SettingsStage.prototype.getOppositeid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.SocketCmd.SettingsStage.prototype.setOppositeid = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string timeToken = 4;
 * @return {string}
 */
proto.SocketCmd.SettingsStage.prototype.getTimetoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.SocketCmd.SettingsStage.prototype.setTimetoken = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional uint32 serverId = 6;
 * @return {number}
 */
proto.SocketCmd.SettingsStage.prototype.getServerid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.SocketCmd.SettingsStage.prototype.setServerid = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * repeated string lightNo = 13;
 * @return {!Array.<string>}
 */
proto.SocketCmd.SettingsStage.prototype.getLightnoList = function() {
  return /** @type {!Array.<string>} */ (jspb.Message.getRepeatedField(this, 13));
};


/** @param {!Array.<string>} value */
proto.SocketCmd.SettingsStage.prototype.setLightnoList = function(value) {
  jspb.Message.setField(this, 13, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.SocketCmd.SettingsStage.prototype.addLightno = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 13, value, opt_index);
};


proto.SocketCmd.SettingsStage.prototype.clearLightnoList = function() {
  this.setLightnoList([]);
};


/**
 * repeated Stage stage = 35;
 * @return {!Array.<!proto.SocketCmd.Stage>}
 */
proto.SocketCmd.SettingsStage.prototype.getStageList = function() {
  return /** @type{!Array.<!proto.SocketCmd.Stage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.SocketCmd.Stage, 35));
};


/** @param {!Array.<!proto.SocketCmd.Stage>} value */
proto.SocketCmd.SettingsStage.prototype.setStageList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 35, value);
};


/**
 * @param {!proto.SocketCmd.Stage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.SocketCmd.Stage}
 */
proto.SocketCmd.SettingsStage.prototype.addStage = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 35, opt_value, proto.SocketCmd.Stage, opt_index);
};


proto.SocketCmd.SettingsStage.prototype.clearStageList = function() {
  this.setStageList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.SocketCmd.Stage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.SocketCmd.Stage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.SocketCmd.Stage.displayName = 'proto.SocketCmd.Stage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.SocketCmd.Stage.prototype.toObject = function(opt_includeInstance) {
  return proto.SocketCmd.Stage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.SocketCmd.Stage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocketCmd.Stage.toObject = function(includeInstance, msg) {
  var f, obj = {
    stage: jspb.Message.getFieldWithDefault(msg, 27, 0),
    stagebegintime: jspb.Message.getFieldWithDefault(msg, 28, ""),
    value: jspb.Message.getFieldWithDefault(msg, 29, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.SocketCmd.Stage}
 */
proto.SocketCmd.Stage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.SocketCmd.Stage;
  return proto.SocketCmd.Stage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.SocketCmd.Stage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.SocketCmd.Stage}
 */
proto.SocketCmd.Stage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 27:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStage(value);
      break;
    case 28:
      var value = /** @type {string} */ (reader.readString());
      msg.setStagebegintime(value);
      break;
    case 29:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.SocketCmd.Stage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.SocketCmd.Stage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.SocketCmd.Stage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.SocketCmd.Stage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStage();
  if (f !== 0) {
    writer.writeUint32(
      27,
      f
    );
  }
  f = message.getStagebegintime();
  if (f.length > 0) {
    writer.writeString(
      28,
      f
    );
  }
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt32(
      29,
      f
    );
  }
};


/**
 * optional uint32 stage = 27;
 * @return {number}
 */
proto.SocketCmd.Stage.prototype.getStage = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/** @param {number} value */
proto.SocketCmd.Stage.prototype.setStage = function(value) {
  jspb.Message.setProto3IntField(this, 27, value);
};


/**
 * optional string stageBeginTime = 28;
 * @return {string}
 */
proto.SocketCmd.Stage.prototype.getStagebegintime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 28, ""));
};


/** @param {string} value */
proto.SocketCmd.Stage.prototype.setStagebegintime = function(value) {
  jspb.Message.setProto3StringField(this, 28, value);
};


/**
 * optional int32 value = 29;
 * @return {number}
 */
proto.SocketCmd.Stage.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 29, 0));
};


/** @param {number} value */
proto.SocketCmd.Stage.prototype.setValue = function(value) {
  jspb.Message.setProto3IntField(this, 29, value);
};


goog.object.extend(exports, proto.SocketCmd);
