// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: settingsStage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SocketCmd {

  /// <summary>Holder for reflection information generated from settingsStage.proto</summary>
  public static partial class SettingsStageReflection {

    #region Descriptor
    /// <summary>File descriptor for settingsStage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SettingsStageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNzZXR0aW5nc1N0YWdlLnByb3RvEglTb2NrZXRDbWQijAEKDVNldHRpbmdz",
            "U3RhZ2USDwoHY21kQ29kZRgBIAEoCRIQCghpZGVudGl0eRgCIAEoCRISCgpv",
            "cHBvc2l0ZUlkGAMgASgJEhAKCHNlcnZlcklkGAYgASgNEh8KBXN0YWdlGCMg",
            "AygLMhAuU29ja2V0Q21kLlN0YWdlEhEKCWNlbGxBZGRycxglIAMoDSI9CgVT",
            "dGFnZRINCgVzdGFnZRgbIAEoDRIWCg5zdGFnZUJlZ2luVGltZRgcIAEoCRIN",
            "CgV2YWx1ZRgdIAEoBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketCmd.SettingsStage), global::SocketCmd.SettingsStage.Parser, new[]{ "CmdCode", "Identity", "OppositeId", "ServerId", "Stage", "CellAddrs" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SocketCmd.Stage), global::SocketCmd.Stage.Parser, new[]{ "Stage_", "StageBeginTime", "Value" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SettingsStage : pb::IMessage<SettingsStage> {
    private static readonly pb::MessageParser<SettingsStage> _parser = new pb::MessageParser<SettingsStage>(() => new SettingsStage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SettingsStage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketCmd.SettingsStageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingsStage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingsStage(SettingsStage other) : this() {
      cmdCode_ = other.cmdCode_;
      identity_ = other.identity_;
      oppositeId_ = other.oppositeId_;
      serverId_ = other.serverId_;
      stage_ = other.stage_.Clone();
      cellAddrs_ = other.cellAddrs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettingsStage Clone() {
      return new SettingsStage(this);
    }

    /// <summary>Field number for the "cmdCode" field.</summary>
    public const int CmdCodeFieldNumber = 1;
    private string cmdCode_ = "";
    /// <summary>
    ///命令号
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CmdCode {
      get { return cmdCode_; }
      set {
        cmdCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "identity" field.</summary>
    public const int IdentityFieldNumber = 2;
    private string identity_ = "";
    /// <summary>
    ///socket对象标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Identity {
      get { return identity_; }
      set {
        identity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "oppositeId" field.</summary>
    public const int OppositeIdFieldNumber = 3;
    private string oppositeId_ = "";
    /// <summary>
    ///操作对端对象标识[可选]
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OppositeId {
      get { return oppositeId_; }
      set {
        oppositeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "serverId" field.</summary>
    public const int ServerIdFieldNumber = 6;
    private uint serverId_;
    /// <summary>
    ///string timeToken = 4;//时间戳yyyy-MM-dd HH:mm:ss.fff
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint ServerId {
      get { return serverId_; }
      set {
        serverId_ = value;
      }
    }

    /// <summary>Field number for the "stage" field.</summary>
    public const int StageFieldNumber = 35;
    private static readonly pb::FieldCodec<global::SocketCmd.Stage> _repeated_stage_codec
        = pb::FieldCodec.ForMessage(282, global::SocketCmd.Stage.Parser);
    private readonly pbc::RepeatedField<global::SocketCmd.Stage> stage_ = new pbc::RepeatedField<global::SocketCmd.Stage>();
    /// <summary>
    ///repeated string lightNo = 13;//路灯标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::SocketCmd.Stage> Stage {
      get { return stage_; }
    }

    /// <summary>Field number for the "cellAddrs" field.</summary>
    public const int CellAddrsFieldNumber = 37;
    private static readonly pb::FieldCodec<uint> _repeated_cellAddrs_codec
        = pb::FieldCodec.ForUInt32(298);
    private readonly pbc::RepeatedField<uint> cellAddrs_ = new pbc::RepeatedField<uint>();
    /// <summary>
    ///单元格数组
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> CellAddrs {
      get { return cellAddrs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SettingsStage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SettingsStage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CmdCode != other.CmdCode) return false;
      if (Identity != other.Identity) return false;
      if (OppositeId != other.OppositeId) return false;
      if (ServerId != other.ServerId) return false;
      if(!stage_.Equals(other.stage_)) return false;
      if(!cellAddrs_.Equals(other.cellAddrs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CmdCode.Length != 0) hash ^= CmdCode.GetHashCode();
      if (Identity.Length != 0) hash ^= Identity.GetHashCode();
      if (OppositeId.Length != 0) hash ^= OppositeId.GetHashCode();
      if (ServerId != 0) hash ^= ServerId.GetHashCode();
      hash ^= stage_.GetHashCode();
      hash ^= cellAddrs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CmdCode.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CmdCode);
      }
      if (Identity.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Identity);
      }
      if (OppositeId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OppositeId);
      }
      if (ServerId != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(ServerId);
      }
      stage_.WriteTo(output, _repeated_stage_codec);
      cellAddrs_.WriteTo(output, _repeated_cellAddrs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CmdCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CmdCode);
      }
      if (Identity.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Identity);
      }
      if (OppositeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OppositeId);
      }
      if (ServerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ServerId);
      }
      size += stage_.CalculateSize(_repeated_stage_codec);
      size += cellAddrs_.CalculateSize(_repeated_cellAddrs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SettingsStage other) {
      if (other == null) {
        return;
      }
      if (other.CmdCode.Length != 0) {
        CmdCode = other.CmdCode;
      }
      if (other.Identity.Length != 0) {
        Identity = other.Identity;
      }
      if (other.OppositeId.Length != 0) {
        OppositeId = other.OppositeId;
      }
      if (other.ServerId != 0) {
        ServerId = other.ServerId;
      }
      stage_.Add(other.stage_);
      cellAddrs_.Add(other.cellAddrs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            CmdCode = input.ReadString();
            break;
          }
          case 18: {
            Identity = input.ReadString();
            break;
          }
          case 26: {
            OppositeId = input.ReadString();
            break;
          }
          case 48: {
            ServerId = input.ReadUInt32();
            break;
          }
          case 282: {
            stage_.AddEntriesFrom(input, _repeated_stage_codec);
            break;
          }
          case 298:
          case 296: {
            cellAddrs_.AddEntriesFrom(input, _repeated_cellAddrs_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Stage : pb::IMessage<Stage> {
    private static readonly pb::MessageParser<Stage> _parser = new pb::MessageParser<Stage>(() => new Stage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Stage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SocketCmd.SettingsStageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stage(Stage other) : this() {
      stage_ = other.stage_;
      stageBeginTime_ = other.stageBeginTime_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Stage Clone() {
      return new Stage(this);
    }

    /// <summary>Field number for the "stage" field.</summary>
    public const int Stage_FieldNumber = 27;
    private uint stage_;
    /// <summary>
    ///阶段1,2,3,4(晨亮)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Stage_ {
      get { return stage_; }
      set {
        stage_ = value;
      }
    }

    /// <summary>Field number for the "stageBeginTime" field.</summary>
    public const int StageBeginTimeFieldNumber = 28;
    private string stageBeginTime_ = "";
    /// <summary>
    ///阶段开始时间戳HH:mm:ss
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StageBeginTime {
      get { return stageBeginTime_; }
      set {
        stageBeginTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 29;
    private int value_;
    /// <summary>
    ///设置值.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Stage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Stage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Stage_ != other.Stage_) return false;
      if (StageBeginTime != other.StageBeginTime) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Stage_ != 0) hash ^= Stage_.GetHashCode();
      if (StageBeginTime.Length != 0) hash ^= StageBeginTime.GetHashCode();
      if (Value != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Stage_ != 0) {
        output.WriteRawTag(216, 1);
        output.WriteUInt32(Stage_);
      }
      if (StageBeginTime.Length != 0) {
        output.WriteRawTag(226, 1);
        output.WriteString(StageBeginTime);
      }
      if (Value != 0) {
        output.WriteRawTag(232, 1);
        output.WriteInt32(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Stage_ != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Stage_);
      }
      if (StageBeginTime.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(StageBeginTime);
      }
      if (Value != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Stage other) {
      if (other == null) {
        return;
      }
      if (other.Stage_ != 0) {
        Stage_ = other.Stage_;
      }
      if (other.StageBeginTime.Length != 0) {
        StageBeginTime = other.StageBeginTime;
      }
      if (other.Value != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 216: {
            Stage_ = input.ReadUInt32();
            break;
          }
          case 226: {
            StageBeginTime = input.ReadString();
            break;
          }
          case 232: {
            Value = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
